import fs from "node:fs";
import path from "node:path";
import type { AppConfig } from "./config.js";

export type SessionRulesOptions = {
  commandPrefix: string;
  repository: string;
  branch: string;
  workDir: string;
  requiredDomains: string[];
};

export function sessionRulesPath(config: AppConfig): string {
  return path.join(config.dataDir, "claude", "hare-m365-agent-rules.md");
}

export function writeSessionRules(
  config: AppConfig,
  options: SessionRulesOptions
): string | undefined {
  if (!config.dataDirPersistent) return undefined;

  const rulesFile = sessionRulesPath(config);
  const contents = buildSessionRules(config, options, rulesFile);
  fs.mkdirSync(path.dirname(rulesFile), { recursive: true });

  if (fs.existsSync(rulesFile) && fs.readFileSync(rulesFile, "utf8") === contents) {
    return rulesFile;
  }

  const temporaryPath = `${rulesFile}.${process.pid}.${Date.now()}.tmp`;
  try {
    fs.writeFileSync(temporaryPath, contents, { encoding: "utf8", mode: 0o600 });
    fs.renameSync(temporaryPath, rulesFile);
  } finally {
    fs.rmSync(temporaryPath, { force: true });
  }
  return rulesFile;
}

function buildSessionRules(
  config: AppConfig,
  options: SessionRulesOptions,
  rulesFile: string
): string {
  const cacheFile = path.join(config.cacheDir, "msal-cache.json");
  const startupCommand = options.commandPrefix;
  const statusCommand = `${options.commandPrefix} auth status`;

  return `# Hare M365 Agent Session Rules

This file is generated by Hare in its persistent data directory. Use it as the source of truth for every Claude/Cowork chat on this machine.

## Fixed locations

- Rules file: ${rulesFile}
- Persistent data directory: ${config.dataDir}
- Login cache: ${cacheFile}
- Downloads: ${config.downloadDir}
- Results: ${config.resultsDir}
- Logs: ${config.logsDir}
- Windows host folder: %USERPROFILE%\\HareM365Agent
- Mac host folder: ~/HareM365Agent

Do not create or select a different Hare data folder. In a new Cowork chat, request access to the existing host HareM365Agent folder and use its mounted root as the data directory above.
Cowork Linux defaults such as /root/.local/share are container-local and are never a persistent Hare data directory.

## Code and commands

- Repository: ${options.repository}
- Branch: ${options.branch}
- Cowork work directory: ${options.workDir}
- Verify latest code with refs/heads/${options.branch} before building.
- Command prefix for this mounted folder:

\`\`\`text
${options.commandPrefix}
\`\`\`

- Startup command:

\`\`\`text
${startupCommand}
\`\`\`

- Authentication status command:

\`\`\`text
${statusCommand}
\`\`\`

Always keep the exact --data-dir argument shown above. A fresh clone does not require a new Microsoft login when this same data directory contains a usable cache.

## Startup state

1. Run the startup command and follow only setup.state and setup.nextCommand.
2. READY means loggedIn and tokenUsable are both true. Do not start a new login; wait for the user's Microsoft 365 request.
3. LOGIN_START_REQUIRED means no usable login exists in this exact data directory. Run setup.nextCommand once and show the returned Microsoft URL and user code.
4. LOGIN_COMPLETE_REQUIRED means wait until the user says the browser login is complete, then run setup.nextCommand once.
5. FOLDER_REQUIRED means the persistent host folder is not mounted. Connect the existing HareM365Agent folder instead of creating another data folder.
6. Do not interpret a temporary /sessions or /tmp data directory as the user's persistent login state.

## Microsoft 365 operation

- Use Hare for requested Outlook, Teams, SharePoint, and OneDrive lookups.
- Default to read-only operation. Sending, posting, uploading, deleting, sharing, and permission changes are unavailable.
- When the user omits a date range, the default lookback is ${config.policy.defaultSearchLookbackDays} days and the actual range must be reported.
- Use outlook count for exact mail counts and sharepoint sites for SharePoint site existence checks.
- Use lastMessageCreatedDateTime, not lastUpdatedDateTime alone, when deciding the latest Teams chat.

## Required domains

${options.requiredDomains.map((domain) => `- ${domain}`).join("\n")}
`;
}
